#!/bin/bash

check_message() {
    INPUT_FILE=$1
	START_LINE=`head -n1 $INPUT_FILE`

	# Patrón con el que debe cumplir el mensaje del commit
	PATTERN="^(REQ) #[[:digit:]]+: "

	if ! [[ "$START_LINE" =~ $PATTERN ]]; then
	  print_message
	  exit 1
	fi
}


print_message() {
	echo -e "\e[1;31m############################\e[0m"
	echo -e "\e[1;31mERROR EN MENSAJE DE COMMIT\e[0m"
	echo -e "\e[1;31m############################\e[0m"
	echo ">> El mensaje del commit no cumple con el estándar del Banco del Austro."
	echo ">> Revise los ejemplos: "
	echo "   REQ #123: mensaje del commit"
}


is_supported_origin() {
	# Se admiten solamente repositorios de Rhodecode (en lugar de la IP hay que usar los nombres de los repositorios)
	SUPPORTED_ORIGIN="10.1.140.41"
	ORIGIN=$(git config --get remote.origin.url)
	if [[ $ORIGIN == *"$SUPPORTED_ORIGIN"* ]]
	then
		return 0
	else
		return 1
	fi
}


if is_supported_origin
then
	check_message "$1"
fi