#!/bin/bash


# ORIGENES SOPORTADOS
# Se admiten solamente repositorios de Rhodecode 
# (en lugar de la IP se podrían usar los nombres de los repositorios o un patrón que combine ambos)
declare -a SUPPORTED_ORIGINS=("10.1.140.41")


INSTALL_DIR_ROOT="$HOME/.baustro"


is_supported_origin() {
	ORIGIN=$(git config --get remote.origin.url)
	for supported in "${SUPPORTED_ORIGINS[@]}"
	do
		if [[ $ORIGIN == *"$supported"* ]]
		then
			return 0 #true in bash
		fi
	done
	return 1 #false in bash
}


is_up_to_date_with_origin() {
	origin=$(git config --get remote.origin.url)
	sha_origin=`git ls-remote "$origin" | head -1 | cut -d '	' -f1`
	sha_local=`git log | head -1 | cut -d ' ' -f2`
	if [ "$sha_origin" = "$sha_local" ]
	then
		return 0
	else
		return 1
	fi
}


do_update() {
	#sh "${INSTALL_DIR_ROOT}/instalar.sh"
	cd ..
	sh instalar.sh
}


execute() {
	if is_supported_origin
	then
		if is_up_to_date_with_origin
		then
			echo "Actualizando estándares del Banco del Austro..."
			do_update
		fi
	fi
}


# FUNCION PRINCIPAL
execute
