#!/bin/bash


# RUTA DE INSTALACIÓN
INSTALL_DIR_ROOT=$(git config --global baustro.installDirRoot)


# ORIGENES SOPORTADOS
# Archivo con la lista de repositorios que deben apegarse al estándar
BLACK_LIST_FILE=$(git config --global baustro.blackListFile)


is_supported_origin() {
	OLDIFS=$IFS
	INPUT="${BLACK_LIST_FILE}"
	exist=false

	if [ -f $INPUT ]
	then
		IFS=$'\r\n' GLOBIGNORE='*' command eval  'lista_negra=($(cat $INPUT))'
		ORIGIN=$(git config --get remote.origin.url)
		for line in "${lista_negra[@]}"
		do
			if [[ $ORIGIN == *"$line"* ]]
			then
				exist=true
				break
			fi
		done
		IFS=$OLDIFS
	fi

	if [[ $exist = true ]]
	then
		return 0	# true in bash
	else
		return 1 	# false in bash
	fi
}


do_update() {
	sh "${INSTALL_DIR_ROOT}/instalar.sh"
}


execute() {
	if is_supported_origin
	then
		do_update
	fi
}


# FUNCION PRINCIPAL
execute